cmake_minimum_required(VERSION 3.22.1)
project(questlink_vr LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(OpenXR REQUIRED CONFIG)
add_library(native_app_glue STATIC ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
target_include_directories(native_app_glue PUBLIC ${ANDROID_NDK}/sources/android/native_app_glue)
add_library(questlink_vr SHARED vr_client.cpp)
target_compile_definitions(questlink_vr PRIVATE XR_USE_PLATFORM_ANDROID XR_USE_GRAPHICS_API_OPENGL_ES)
target_include_directories(questlink_vr PRIVATE ../../../../../questlink-common)
target_link_libraries(questlink_vr PRIVATE native_app_glue OpenXR::openxr_loader android log EGL GLESv3 jnigraphics mediandk)
target_link_options(questlink_vr PRIVATE "-uANativeActivity_onCreate")
target_compile_options(questlink_vr PRIVATE -Wall -Wextra)
